/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apple.istore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**

/**
 *
 * @author pulas
 */
public class cashiermenu extends javax.swing.JFrame {

    /**
     * Creates new form cashiermenu
     */
    public cashiermenu() {
        initComponents();
        getAllSales();
        getAllProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productid = new javax.swing.JTextField();
        cashiername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cashsell = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selltable = new javax.swing.JTable();
        cashremove = new javax.swing.JButton();
        quantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("quantity");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 165, -1, -1));

        jLabel2.setText("Cashier Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 80, 85, -1));
        jPanel2.add(productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 77, 144, -1));

        cashiername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashiernameActionPerformed(evt);
            }
        });
        jPanel2.add(cashiername, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 122, 144, -1));

        jLabel3.setText("product name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
        jPanel2.add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 144, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setText(" CASHIERS MENU");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 6, 365, -1));

        jLabel6.setText("price");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 74, -1));

        cashsell.setBackground(new java.awt.Color(153, 255, 255));
        cashsell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cashsell.setText("sell");
        cashsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashsellMouseClicked(evt);
            }
        });
        cashsell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashsellActionPerformed(evt);
            }
        });
        jPanel2.add(cashsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 144, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("APPLE iSTORE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 756, 153, 35));

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 192, 83, 21));

        selltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "casier name", "product name", "product id", "quantity", "price"
            }
        ));
        selltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selltableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(selltable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 256, 625, 203));

        cashremove.setBackground(new java.awt.Color(153, 255, 255));
        cashremove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cashremove.setText("remove");
        cashremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashremoveMouseClicked(evt);
            }
        });
        cashremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashremoveActionPerformed(evt);
            }
        });
        jPanel2.add(cashremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 162, 144, -1));

        jLabel7.setText("product id");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 125, -1, -1));

        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "product id", "product  name", "quantity", "price"
            }
        ));
        jScrollPane3.setViewportView(producttable);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 509, 625, 191));

        view.setBackground(new java.awt.Color(153, 255, 255));
        view.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view.setText("view");
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("transaction records");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 218, 157, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("storage table");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 477, -1, -1));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 140, -1));

        jLabel10.setText("search");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     void getAllSales(){
           try {
            // TODO add your handling code here:
            String url="jdbc:derby:C:\\new database\\newtest;create=true";
     
          
                Connection con = DriverManager.getConnection(url);
                String sql = "select * from CASHIERSALES";
                PreparedStatement stmt = con.prepareStatement(sql);
                 ResultSet resultSet=stmt.executeQuery();
                 ResultSetMetaData rsmd=resultSet.getMetaData();
                 int n=rsmd.getColumnCount();
                 DefaultTableModel dtm=(DefaultTableModel) selltable.getModel();
                 dtm.setRowCount(0);
                 while(resultSet.next()){
                     Vector v=new Vector();
                     for(int i=1; i<=n; i++){
                         v.add(resultSet.getString("PRODUCTID"));
                         v.add(resultSet.getString("PRODUCTNAME"));
                         v.add(resultSet.getString("CASHIERNAME"));
                         v.add(resultSet.getString("QUANTITY"));
                         v.add(resultSet.getString("PRICE"));
                     }
                     
                      dtm.addRow(v);
                 }
                
//                

                  
                
        } catch (Exception ex) {
          System.out.println(ex);
        }
        
    }
    
    
      void getAllProducts(){
           try {
            // TODO add your handling code here:
            String url="jdbc:derby:C:\\new database\\newtest;create=true";
     
          
                Connection con = DriverManager.getConnection(url);
                String sql = "select * from PRODUCTS";
                PreparedStatement stmt = con.prepareStatement(sql);
                 ResultSet resultSet=stmt.executeQuery();
                 ResultSetMetaData rsmd=resultSet.getMetaData();
                 int n=rsmd.getColumnCount();
                 DefaultTableModel dtm=(DefaultTableModel) producttable.getModel();
                 dtm.setRowCount(0);
                   while(resultSet.next()){
                     Vector v=new Vector();
                     for(int i=1; i<=n; i++){
                     
                         v.add(resultSet.getString("PRODUCTID"));
                         v.add(resultSet.getString("PRODUCTNAME"));                    
                         v.add(resultSet.getString("QUANTITY"));
                         v.add(resultSet.getString("PRICE"));
                     }
                     
                      dtm.addRow(v);
                 }
                
               
//                

                  
                
        } catch (Exception ex) {
          System.out.println(ex);
        }
      }
      
        
    private void cashiernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashiernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashiernameActionPerformed

    private void cashsellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashsellMouseClicked

    }//GEN-LAST:event_cashsellMouseClicked

    private void cashsellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashsellActionPerformed
        try {
            
            String url="jdbc:derby:C:\\new database\\newtest;create=true";
          
                Connection con = DriverManager.getConnection(url);
                String sql = "INSERT INTO CASHIERSALES ( PRODUCTID, PRODUCTNAME,CASHIERNAME,QUANTITY, PRICE) VALUES (?, ?, ?, ?,?)";
                PreparedStatement stmt = con.prepareStatement(sql);

                stmt.setString(1, productid.getText());
                stmt.setString(2, productname.getText());
                stmt.setString(3, cashiername.getText());
                stmt.setString(4, quantity.getText());
                stmt.setString(5, price.getText());
               

                int rows=stmt.executeUpdate();
                if(rows>0){
                    System.out.println("ok");
                   
                    getAllSales();
                    JOptionPane.showMessageDialog(null, "sale added successfully");
                    cashiermenu cashmenu=new cashiermenu();
                    cashmenu.setVisible(true);
                    this.dispose();
                    
      
                }
        } catch (Exception ex) {
          ex.printStackTrace();
               
        }

        //

    }//GEN-LAST:event_cashsellActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
cashierlogin cashlog =new cashierlogin();
cashlog.setVisible(true);
this.dispose();
        
    }//GEN-LAST:event_backActionPerformed

    private void cashremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashremoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cashremoveMouseClicked

    private void cashremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashremoveActionPerformed
        // TODO add your handling code here:
        String sql="delete FROM CASHIERSALES WHERE PRODUCTID=?"; 
        
       try{
            String url="jdbc:derby:C:\\new database\\newtest;create=true";
            Connection con = DriverManager.getConnection(url);
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, productid.getText());
           
           
          int rows= stmt.executeUpdate();
          if(rows>0){
              JOptionPane.showMessageDialog(null, "removed");   //if the operation is sucecss removed willshow
          }
           getAllSales();           //calling sales method
          
              
       }catch(Exception e){ 
           JOptionPane.showMessageDialog(null, "Error");
       }
    }//GEN-LAST:event_cashremoveActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void selltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selltableMouseClicked
        // TODO add your handling code here:
        {
            String selectedCellValue = (String) selltable.getValueAt(selltable.getSelectedRow() , selltable.getSelectedColumn());
            productid.setText(selectedCellValue);
        }
    }//GEN-LAST:event_selltableMouseClicked

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        getAllProducts();
    }//GEN-LAST:event_viewActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
         DefaultTableModel obj=(DefaultTableModel) producttable.getModel(); //selcting the table for data searching d
       TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
       producttable.setRowSorter(obj1);   // sortingout row by row in the table
       obj1.setRowFilter(RowFilter.regexFilter(search.getText()));
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashiermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashiermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashiermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashiermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashiermenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField cashiername;
    private javax.swing.JButton cashremove;
    private javax.swing.JButton cashsell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productid;
    private javax.swing.JTextField productname;
    private javax.swing.JTable producttable;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField search;
    private javax.swing.JTable selltable;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
